theme: material
site_name: Dms
docs_dir: src
site_dir: build
repo_name: agreyfox/dms
repo_url: https://github.com/agreyfox/dms

markdown_extensions:
      - codehilite(linenums=false)
      - meta
      - admonition
      - toc(permalink=true)

google_analytics:
      - 'UA-98609560-1'
      - auto

extra:
  palette:
    primary: grey
    accent: light-blue
  social:
    - type: github
      link: https://github.com/agreyfox
    - type: twitter
      link: https://twitter.com/agreyfox
  logo: images/logo.png
